import type { ChartConfig, Row, Chair, InstrumentType } from './types'

export interface PresetSection {
  name: string
  instrument: string
  count: number
  color: string
  // 'solo' = each chair gets a stand, 'shared' = pairs share one stand,
  // 'none' = no stands. Default is 'solo' when unspecified.
  standMode?: 'solo' | 'shared' | 'none'
}

// Explicit row composition — used when a preset needs specific chair labels
// per seat (e.g. "Tnr 1", "Alto 2") rather than a generic packed layout.
export interface PresetCustomChair {
  label: string
  color: string
  hasStand?: boolean
  standAfter?: boolean
  // Default true. Set to false for a disabled placeholder chair that keeps
  // the row shape intact without representing a real player.
  enabled?: boolean
}
export interface PresetCustomRow {
  label: string
  chairs: PresetCustomChair[]
}

// Pre-placed fixed instrument in polar coords relative to the conductor.
export interface PresetInstrument {
  type: InstrumentType
  angle: number       // canvas radians: 0 right, π/2 down, π left, -π/2 up
  distance: number    // pixels from conductor
  rotation?: number   // default 0
  count?: number      // for timpani
  label?: string
}

export interface Preset {
  id: string
  name: string
  layout: ChartConfig['layout']
  sections: PresetSection[]
  // Optional: when set, these explicit rows override `sections` packing.
  customRows?: PresetCustomRow[]
  // Optional: Boosey & Hawkes orchestra notation. When present, the rows are
  // generated by parseOrchestraNotation + buildOrchestraRows and override
  // both `sections` and `customRows`.
  notation?: string
  // Optional: number of straight rows from the back (semicircle layouts).
  straightRows?: number
  // Optional: pre-placed fixed instruments. When omitted, instruments are
  // simply cleared on apply (which is the default for every preset).
  instruments?: PresetInstrument[]
}

// Colors are visually distinct and print-friendly
const COLORS = {
  woodwind:   '#a8d8ea',
  brass:      '#f9ca74',
  percussion: '#c7b8ea',
  strings:    '#a8e6cf',
  rhythm:     '#f4a261',
  voice:      '#e8c4c4',
}

export const PRESETS: Preset[] = [
  {
    id: 'big-band',
    name: 'Big Band',
    layout: 'straight',
    sections: [],
    // Three straight rows: saxes (front, 5) → trombones (mid, 4) → trumpets (back, 4).
    // Standard big-band lead-in-the-middle ordering within each section.
    // Every player gets their own music stand.
    customRows: [
      {
        label: 'A',
        chairs: [
          { label: 'Tnr 2',  color: COLORS.woodwind, hasStand: true },
          { label: 'Alto 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Alto 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Tnr 1',  color: COLORS.woodwind, hasStand: true },
          { label: 'Bari',   color: COLORS.woodwind, hasStand: true },
        ],
      },
      {
        label: 'B',
        chairs: [
          { label: 'Tbn 4', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 2', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 3', color: COLORS.brass, hasStand: true },
        ],
      },
      {
        label: 'C',
        chairs: [
          { label: 'Tpt 4', color: '#f4a261', hasStand: true },
          { label: 'Tpt 2', color: '#f4a261', hasStand: true },
          { label: 'Tpt 1', color: '#f4a261', hasStand: true },
          { label: 'Tpt 3', color: '#f4a261', hasStand: true },
        ],
      },
    ],
    instruments: [
      { type: 'bass-amp',   angle: -2.25, distance: 245 },
      { type: 'drumkit',    angle: -2.05, distance: 235 },
      { type: 'piano',      angle: -2.55, distance: 215 },
      { type: 'guitar-amp', angle: -2.25, distance: 170 },
    ],
  },
  {
    id: 'chamber-orchestra',
    name: 'Chamber Orchestra',
    layout: 'semicircle',
    sections: [],
    // Mozart-sized: 1 each of Fl/Ob/Cl/Bn, 2 horns, no perc, modest strings,
    // 1 bass sitting in the third row behind the cellos.
    notation: '1.1.1.1 - 2.0.0.0 - 0 - 6.5.4.3.1',
  },
  {
    id: 'full-symphony',
    name: 'Full Symphony',
    layout: 'semicircle',
    sections: [],
    // Late-romantic full symphony (Tchaikovsky-ish): triple winds, full
    // brass, timpani + perc, full strings.
    notation: '3.3.3.3 - 4.3.3.1 - 1.2 - 14.12.10.8.6',
  },
  {
    id: 'concert-band',
    name: 'Concert Band',
    layout: 'semicircle',
    sections: [],
    // Four concentric rows fan back from the conductor with chair counts
    // 8 / 10 / 7 / 19 (front to back). Every player gets their own stand —
    // no shared desks in a concert band. The percussion section lives at
    // the back as a row of large fixed instruments (mallets, aux, drum
    // kit, timpani) plus a bass amp tucked behind the back row.
    customRows: [
      {
        label: 'A',
        chairs: [
          { label: 'Cl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Ob',   color: COLORS.woodwind, hasStand: true },
          { label: 'Bsn',  color: COLORS.woodwind, hasStand: true },
        ],
      },
      {
        label: 'B',
        chairs: [
          { label: 'Cl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 3', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 3', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 3', color: COLORS.woodwind, hasStand: true },
          { label: 'B Cl', color: COLORS.woodwind, hasStand: true },
          { label: 'Bsn',  color: COLORS.woodwind, hasStand: true },
        ],
      },
      {
        label: 'C',
        // 7 saxes centred in 11 slots — 2 disabled placeholder chairs on
        // each side so the saxes cluster behind the clarinets instead of
        // stretching to the edges of the arc.
        chairs: [
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: 'AS 1', color: COLORS.woodwind, hasStand: true },
          { label: 'AS 1', color: COLORS.woodwind, hasStand: true },
          { label: 'AS 2', color: COLORS.woodwind, hasStand: true },
          { label: 'AS 2', color: COLORS.woodwind, hasStand: true },
          { label: 'TS',   color: COLORS.woodwind, hasStand: true },
          { label: 'TS',   color: COLORS.woodwind, hasStand: true },
          { label: 'BS',   color: COLORS.woodwind, hasStand: true },
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: '',     color: COLORS.woodwind, enabled: false },
        ],
      },
      {
        label: 'D',
        chairs: [
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Tpt 3', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 3', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 2', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 2', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 1', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 2', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 2', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 3', color: COLORS.brass, hasStand: true },
          { label: 'Euph',  color: COLORS.brass, hasStand: true },
          { label: 'Euph',  color: COLORS.brass, hasStand: true },
          { label: 'Tuba',  color: COLORS.brass, hasStand: true },
          { label: 'Tuba',  color: COLORS.brass, hasStand: true },
        ],
      },
    ],
    instruments: [
      // Drum Kit and Aux at the top centre / centre-right.
      // Mallets curve around the LEFT side of the back arc, each rotated
      // so its long axis is tangent to the curve (radial-out from the
      // conductor). Timpani sits at the top-right; bass amp tucks in to
      // its lower-right, behind the euph/tuba area of the back chair row.
      // Polar coords from the conductor.
      { type: 'drumkit',  angle: -1.27, distance: 470 },
      { type: 'square',   angle: -1.55, distance: 440, label: 'Aux' },
      { type: 'mallet',   angle: -1.92, distance: 460, label: 'Glock',   rotation: -0.35 },
      { type: 'mallet',   angle: -2.22, distance: 445, label: 'Xylo',    rotation: -0.65 },
      { type: 'mallet',   angle: -2.53, distance: 445, label: 'Vibes',   rotation: -0.96 },
      { type: 'mallet',   angle: -2.80, distance: 445, label: 'Marimba', rotation: -1.23 },
      { type: 'timpani',  angle: -0.95, distance: 490, count: 4 },
      { type: 'bass-amp', angle: -0.37, distance: 435 },
    ],
  },
  {
    id: 'string-quartet',
    name: 'String Quartet',
    layout: 'semicircle',
    sections: [
      { name: 'Violin I',  instrument: 'Violin', count: 1, color: COLORS.strings, standMode: 'solo' },
      { name: 'Violin II', instrument: 'Violin', count: 1, color: COLORS.strings, standMode: 'solo' },
      { name: 'Viola',     instrument: 'Viola',  count: 1, color: COLORS.strings, standMode: 'solo' },
      { name: 'Cello',     instrument: 'Cello',  count: 1, color: COLORS.strings, standMode: 'solo' },
    ],
  },
  {
    id: 'jazz-combo',
    name: 'Jazz Combo',
    layout: 'semicircle',
    sections: [
      { name: 'Trumpet',  instrument: 'Trumpet',  count: 1, color: COLORS.brass,    standMode: 'solo' },
      { name: 'Saxophone',instrument: 'Sax',      count: 1, color: COLORS.woodwind, standMode: 'solo' },
      { name: 'Piano',    instrument: 'Piano',    count: 1, color: COLORS.rhythm,   standMode: 'solo' },
      { name: 'Guitar',   instrument: 'Guitar',   count: 1, color: COLORS.rhythm,   standMode: 'solo' },
      { name: 'Bass',     instrument: 'Bass',     count: 1, color: COLORS.rhythm,   standMode: 'solo' },
      { name: 'Drums',    instrument: 'Drums',    count: 1, color: COLORS.rhythm,   standMode: 'solo' },
    ],
  },
]

// ---------------------------------------------------------------------------
// Section → Row packing
// ---------------------------------------------------------------------------

/**
 * Convert a preset + optional count overrides into a ChartConfig-ready row array.
 * Sections are packed into rows of maxPerRow chairs, colored by section.
 * Stands are applied per-section based on standMode (default 'solo').
 */
export function buildRowsFromSections(
  sections: PresetSection[],
  maxPerRow = 12,
): Row[] {
  // Flatten all chairs with stands applied per section
  const allChairs: Chair[] = []
  for (const section of sections) {
    const standMode = section.standMode ?? 'solo'
    for (let i = 0; i < section.count; i++) {
      const chair: Chair = {
        id: crypto.randomUUID(),
        enabled: true,
        color: section.color,
        label: section.instrument,
        hasStand: standMode === 'solo',
        standAfter: standMode === 'shared' && (i % 2 === 0) && (i + 1 < section.count),
      }
      allChairs.push(chair)
    }
  }

  // Pack into rows
  const rows: Row[] = []
  let i = 0
  const rowLabels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  while (i < allChairs.length) {
    const rowChairs = allChairs.slice(i, i + maxPerRow)
    rows.push({
      id: crypto.randomUUID(),
      chairs: rowChairs,
      label: rowLabels[rows.length] ?? String(rows.length + 1),
      fontSize: 11,
    })
    i += maxPerRow
  }

  return rows
}

// ---------------------------------------------------------------------------
// Boosey & Hawkes orchestra notation
//
// Format: `Ww - Br [- Perc] - Str` — each block is a dot-separated list of
// player counts. A count may carry a parenthesised doubling list, e.g.
// `3(III=Bass Clarinet)` or `2(I=Picc, II=Alto Fl)`.
//
// Examples:
//   2.2.2.2 - 4.2.3.1 - 1.2 - 12.10.8.8.6   (Brahms-sized)
//   1.1.1.1 - 2.0.0.0 - 0 - 6.5.4.3.2       (Mozart-sized chamber)
//   3.3.3.3 - 4.3.3.1 - 1.2 - 14.12.10.8.6  (Tchaikovsky-sized)
// ---------------------------------------------------------------------------

const ROMAN_TO_INT: Record<string, number> = {
  I: 1, II: 2, III: 3, IV: 4, V: 5, VI: 6, VII: 7, VIII: 8, IX: 9, X: 10,
}

interface ParsedInstrument {
  count: number
  doublings: Map<number, string>   // 1-indexed position → doubling label
}

interface ParsedSlot {
  name: string                     // canonical short name (e.g. "Fl")
  parsed: ParsedInstrument
}

export interface OrchestraComposition {
  woodwinds: ParsedSlot[]
  brass: ParsedSlot[]
  percussion: ParsedSlot[]
  strings: ParsedSlot[]
}

const WW_NAMES   = ['Fl', 'Ob', 'Cl', 'Bn']
const BR_NAMES   = ['Hn', 'Tp', 'Tb', 'Tu']
const PERC_NAMES = ['Timp', 'Perc']
const STR_NAMES  = ['V1', 'V2', 'Va', 'Vc', 'Cb']

function parseEntry(entry: string): ParsedInstrument {
  const trimmed = entry.trim()
  if (!trimmed || trimmed === '0') return { count: 0, doublings: new Map() }
  const m = trimmed.match(/^(\d+)(?:\((.+)\))?$/)
  if (!m) return { count: 0, doublings: new Map() }
  const count = parseInt(m[1], 10)
  const doublings = new Map<number, string>()
  if (m[2]) {
    for (const part of m[2].split(',').map(s => s.trim())) {
      const eq = part.indexOf('=')
      if (eq < 0) continue
      const posRaw = part.slice(0, eq).trim().toUpperCase()
      const label = part.slice(eq + 1).trim()
      const idx = ROMAN_TO_INT[posRaw] ?? parseInt(posRaw, 10)
      if (idx && label) doublings.set(idx, label)
    }
  }
  return { count, doublings }
}

function parseBlock(block: string, names: string[]): ParsedSlot[] {
  return block.split('.').map((entry, i) => ({
    name: names[i] ?? `?${i + 1}`,
    parsed: parseEntry(entry),
  }))
}

export function parseOrchestraNotation(notation: string): OrchestraComposition | null {
  const blocks = notation.split(/\s*-\s*/).map(b => b.trim()).filter(b => b)
  if (blocks.length < 3 || blocks.length > 4) return null
  let wwBlock: string, brBlock: string, percBlock: string | null = null, strBlock: string
  if (blocks.length === 3) {
    [wwBlock, brBlock, strBlock] = blocks
  } else {
    [wwBlock, brBlock, percBlock, strBlock] = blocks
  }
  return {
    woodwinds:  parseBlock(wwBlock,  WW_NAMES),
    brass:      parseBlock(brBlock,  BR_NAMES),
    percussion: percBlock ? parseBlock(percBlock, PERC_NAMES) : [],
    strings:    parseBlock(strBlock, STR_NAMES),
  }
}

/** Human-readable summary of a parsed composition, used by the modal preview. */
export function describeComposition(comp: OrchestraComposition): string {
  const longNames: Record<string, string> = {
    Fl: 'Flute', Ob: 'Oboe', Cl: 'Clarinet', Bn: 'Bassoon',
    Hn: 'French Horn', Tp: 'Trumpet', Tb: 'Trombone', Tu: 'Tuba',
    Timp: 'Timpani', Perc: 'Percussion',
    V1: 'Violin I', V2: 'Violin II', Va: 'Viola', Vc: 'Cello', Cb: 'Double Bass',
  }
  const lines: string[] = []
  const fmtBlock = (label: string, slots: ParsedSlot[]) => {
    const parts = slots
      .filter(s => s.parsed.count > 0)
      .map(s => {
        const long = longNames[s.name] ?? s.name
        const dbl = [...s.parsed.doublings.entries()]
          .map(([pos, lab]) => `${pos === 1 ? 'I' : pos === 2 ? 'II' : pos === 3 ? 'III' : String(pos)}=${lab}`)
          .join(', ')
        const annot = dbl ? ` (${dbl})` : ''
        return `${s.parsed.count} ${long}${annot}`
      })
    if (parts.length) lines.push(`${label}: ${parts.join(', ')}`)
  }
  fmtBlock('Woodwinds',  comp.woodwinds)
  fmtBlock('Brass',      comp.brass)
  fmtBlock('Percussion', comp.percussion)
  fmtBlock('Strings',    comp.strings)
  const total = [...comp.woodwinds, ...comp.brass, ...comp.percussion, ...comp.strings]
    .reduce((s, slot) => s + slot.parsed.count, 0)
  lines.push(`Total: ${total} players`)
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Build rows from a parsed orchestra composition.
//
// Layout strategy (semicircle, conductor at front):
//  - Strings closest to the conductor (innermost arc), grouped together.
//    Larger orchestras split strings across multiple rows; smaller ones
//    pack all bowed strings into one front row with bass behind.
//  - Winds in 1–2 rows behind strings (Fl/Ob front, Cl/Bn back when wide).
//  - Brass behind winds.
//  - Percussion in the back row.
//
// Stand placement:
//  - Strings get shared stands (every two players share).
//  - Winds, brass, percussion get solo stands (one per player).
// ---------------------------------------------------------------------------

function makeChairFromSlot(slot: ParsedSlot, chairIndex: number, color: string, mode: 'solo' | 'shared'): Chair {
  const dbl = slot.parsed.doublings.get(chairIndex + 1)
  const label = dbl ? `${slot.name}/${dbl}` : slot.name
  return {
    id: crypto.randomUUID(),
    enabled: true,
    color,
    label,
    hasStand: mode === 'solo',
    standAfter: false,   // set later for shared mode at the row level
  }
}

// A disabled placeholder used to keep the semicircle row shape consistent
// when a string section runs out of players in the back rows.
function makePlaceholderChair(color: string): Chair {
  return {
    id: crypto.randomUUID(),
    enabled: false,
    color,
    label: '',
    hasStand: false,
    standAfter: false,
  }
}

function rowFromSlots(
  slots: ParsedSlot[],
  color: string,
  mode: 'solo' | 'shared',
  rowLabel: string,
): Row | null {
  const chairs: Chair[] = []
  for (const slot of slots) {
    if (!slot || slot.parsed.count === 0) continue
    const sectionStart = chairs.length
    for (let i = 0; i < slot.parsed.count; i++) {
      chairs.push(makeChairFromSlot(slot, i, color, mode))
    }
    // For shared mode, pair stands within this section only (so no shared
    // stand bridges across two different instrument groups in the same row).
    if (mode === 'shared') {
      for (let i = sectionStart; i + 1 < sectionStart + slot.parsed.count; i += 2) {
        chairs[i].standAfter = true
      }
    }
  }
  if (chairs.length === 0) return null
  return {
    id: crypto.randomUUID(),
    chairs,
    label: rowLabel,
    fontSize: 11,
  }
}

export interface OrchestraRowsResult {
  rows: Row[]
  /** Number of rows from the back to render as straight lines instead of arcs.
   *  Bowed string sections (V1/V2/Va/Vc) sit in the front arc; everything
   *  behind them (Cb, winds, brass, percussion) renders in straight rows so
   *  small sections like a pair of horns don't get stretched across the
   *  whole back of the stage. */
  straightRows: number
}

export function buildOrchestraRows(comp: OrchestraComposition): OrchestraRowsResult {
  const rows: Row[] = []
  const labels = 'ABCDEFGHIJKLMN'
  let arcRowCount = 0
  const pushRow = (chairs: Chair[], isArc: boolean) => {
    if (chairs.length === 0) return
    rows.push({
      id: crypto.randomUUID(),
      chairs,
      label: labels[rows.length] ?? String(rows.length + 1),
      fontSize: 11,
    })
    if (isArc) arcRowCount++
  }
  const pushSectionRow = (slots: ParsedSlot[], color: string, mode: 'solo' | 'shared') => {
    const r = rowFromSlots(slots, color, mode, '')
    if (r) pushRow(r.chairs, false)
  }

  // ---- Strings: integrated semicircle rows, slot-aware, with back-row doubling ----
  // Layout rules:
  //   * Each row has one column per active string section, in left-to-right
  //     order V1 | V2 | Va | (Vc → Cb). The rightmost column is shared:
  //     cellos fill the front of that column, basses take over behind them.
  //   * Rows 0–3 get 1 desk per section (a tight front for the principals).
  //   * Rows 4+ get 2 desks per section (the section spreads back faster,
  //     matching real orchestra seating).
  //   * Exhausted sections in a row get placeholder desks so the slot count
  //     and column structure stay consistent across the row.
  //   * Within a section, an odd lone last chair gets its own solo stand
  //     instead of a half-desk.
  const v1 = comp.strings[0], v2 = comp.strings[1], va = comp.strings[2], vc = comp.strings[3], cb = comp.strings[4]
  const v1Desks = v1?.parsed.count ? Math.ceil(v1.parsed.count / 2) : 0
  const v2Desks = v2?.parsed.count ? Math.ceil(v2.parsed.count / 2) : 0
  const vaDesks = va?.parsed.count ? Math.ceil(va.parsed.count / 2) : 0
  const vcDesks = vc?.parsed.count ? Math.ceil(vc.parsed.count / 2) : 0
  const cbDesks = cb?.parsed.count ? Math.ceil(cb.parsed.count / 2) : 0
  const rightTotal = vcDesks + cbDesks

  if (v1Desks + v2Desks + vaDesks + rightTotal > 0) {
    // Returns the chairs for one desk position. Full desk (2 paired chairs),
    // lone last chair (1 chair, solo stand), or placeholder pair (2 disabled).
    const oneDesk = (slot: ParsedSlot, deskIdx: number): Chair[] => {
      const startIdx = deskIdx * 2
      const remaining = slot.parsed.count - startIdx
      if (remaining >= 2) {
        const c1 = makeChairFromSlot(slot, startIdx,     COLORS.strings, 'shared')
        const c2 = makeChairFromSlot(slot, startIdx + 1, COLORS.strings, 'shared')
        c1.standAfter = true
        return [c1, c2]
      }
      if (remaining === 1) {
        return [makeChairFromSlot(slot, startIdx, COLORS.strings, 'solo')]
      }
      return [makePlaceholderChair(COLORS.strings), makePlaceholderChair(COLORS.strings)]
    }
    const placeholderDesk = (): Chair[] => [
      makePlaceholderChair(COLORS.strings),
      makePlaceholderChair(COLORS.strings),
    ]

    // Each column tracks how many desks it has already placed, then hands
    // out the next `n` desks on request (padding with placeholder desks
    // once its real desks are exhausted).
    let v1Used = 0, v2Used = 0, vaUsed = 0, rightUsed = 0
    const takeFrom = (
      slot: ParsedSlot | undefined,
      used: () => number,
      bump: () => void,
      total: number,
      n: number,
    ): Chair[] => {
      const out: Chair[] = []
      for (let i = 0; i < n; i++) {
        if (slot && used() < total) {
          out.push(...oneDesk(slot, used()))
          bump()
        } else {
          out.push(...placeholderDesk())
        }
      }
      return out
    }
    const takeRight = (n: number): Chair[] => {
      const out: Chair[] = []
      for (let i = 0; i < n; i++) {
        if (vc && rightUsed < vcDesks) {
          out.push(...oneDesk(vc, rightUsed))
          rightUsed++
        } else if (cb && rightUsed < rightTotal) {
          out.push(...oneDesk(cb, rightUsed - vcDesks))
          rightUsed++
        } else {
          out.push(...placeholderDesk())
        }
      }
      return out
    }

    let row = 0
    // Keep going until every active column has placed all its real desks.
    while (v1Used < v1Desks || v2Used < v2Desks || vaUsed < vaDesks || rightUsed < rightTotal) {
      const desksPerSection = row < 4 ? 1 : 2
      // Separator placeholders between adjacent section columns scale with
      // how far back we are. The front rows have a small natural arc, so
      // extra padding cramps them; the back rows have a wide arc where the
      // desks would otherwise drift apart and lose their visual grouping.
      //   Rows 0-1: no separators (tight front).
      //   Row 2:    1 separator chair between sections.
      //   Rows 3+:  2 separator chairs between sections.
      const sepCount = row < 2 ? 0 : row < 3 ? 1 : 2
      const cols: Chair[][] = []
      if (v1Desks > 0)    cols.push(takeFrom(v1, () => v1Used, () => { v1Used++ }, v1Desks, desksPerSection))
      if (v2Desks > 0)    cols.push(takeFrom(v2, () => v2Used, () => { v2Used++ }, v2Desks, desksPerSection))
      if (vaDesks > 0)    cols.push(takeFrom(va, () => vaUsed, () => { vaUsed++ }, vaDesks, desksPerSection))
      if (rightTotal > 0) cols.push(takeRight(desksPerSection))

      const rowChairs: Chair[] = []
      for (let i = 0; i < cols.length; i++) {
        rowChairs.push(...cols[i])
        if (i < cols.length - 1) {
          for (let s = 0; s < sepCount; s++) {
            rowChairs.push(makePlaceholderChair(COLORS.strings))
          }
        }
      }
      pushRow(rowChairs, true)
      row++
    }
  }

  // ---- Winds: solo stands, one or two straight rows ----
  const fl = comp.woodwinds[0], ob = comp.woodwinds[1], cl = comp.woodwinds[2], bn = comp.woodwinds[3]
  const totalWinds = comp.woodwinds.reduce((s, slot) => s + (slot?.parsed.count ?? 0), 0)
  const splitWinds = totalWinds > 6 &&
    ((fl?.parsed.count ?? 0) + (ob?.parsed.count ?? 0)) > 0 &&
    ((cl?.parsed.count ?? 0) + (bn?.parsed.count ?? 0)) > 0
  if (splitWinds) {
    pushSectionRow([fl, ob], COLORS.woodwind, 'solo')
    pushSectionRow([cl, bn], COLORS.woodwind, 'solo')
  } else if (totalWinds > 0) {
    pushSectionRow(comp.woodwinds, COLORS.woodwind, 'solo')
  }

  // ---- Brass: one straight row ----
  if (comp.brass.reduce((s, slot) => s + slot.parsed.count, 0) > 0) {
    pushSectionRow(comp.brass, COLORS.brass, 'solo')
  }

  // ---- Percussion: back straight row ----
  if (comp.percussion.reduce((s, slot) => s + slot.parsed.count, 0) > 0) {
    pushSectionRow(comp.percussion, COLORS.percussion, 'solo')
  }

  return { rows, straightRows: rows.length - arcRowCount }
}
