import type { ChartConfig, Row, Chair, FixedInstrument, InstrumentType } from './types'

export interface PresetSection {
  name: string
  instrument: string
  count: number
  color: string
  // 'solo' = each chair gets a stand, 'shared' = pairs share one stand,
  // 'none' = no stands. Default is 'solo' when unspecified.
  standMode?: 'solo' | 'shared' | 'none'
}

// Explicit row composition — used when a preset needs specific chair labels
// per seat (e.g. "Tnr 1", "Alto 2") rather than a generic packed layout.
export interface PresetCustomChair {
  label: string
  color: string
  hasStand?: boolean
  standAfter?: boolean
  // Default true. Set to false for a disabled placeholder chair that keeps
  // the row shape intact without representing a real player.
  enabled?: boolean
  isStool?: boolean
}
export interface PresetCustomRow {
  label: string
  chairs: PresetCustomChair[]
  // Optional straight-row geometry baked into the preset (px between chairs /
  // sideways shift of the row centre), e.g. to leave room for fixed
  // instruments. Map to Row.straightSpacing / straightOffset.
  straightSpacing?: number
  straightOffset?: number
}

// Pre-placed fixed instrument in polar coords relative to the conductor.
export interface PresetInstrument {
  type: InstrumentType
  angle: number       // canvas radians: 0 right, π/2 down, π left, -π/2 up
  distance: number    // pixels from conductor
  rotation?: number   // default 0
  count?: number      // for timpani
  label?: string
}

export interface Preset {
  id: string
  name: string
  layout: ChartConfig['layout']
  sections: PresetSection[]
  // Optional: when set, these explicit rows override `sections` packing.
  customRows?: PresetCustomRow[]
  // Optional: Boosey & Hawkes orchestra notation. When present, the rows are
  // generated by parseOrchestraNotation + buildOrchestraRows and override
  // both `sections` and `customRows`.
  notation?: string
  // Optional: number of straight rows from the back (semicircle layouts).
  straightRows?: number
  // Optional: pre-placed fixed instruments. When omitted, instruments are
  // simply cleared on apply (which is the default for every preset).
  instruments?: PresetInstrument[]
}

// Colors are visually distinct and print-friendly
const COLORS = {
  woodwind:   '#a8d8ea',
  brass:      '#f9ca74',
  percussion: '#c7b8ea',
  strings:    '#a8e6cf',
  rhythm:     '#f4a261',
  voice:      '#e8c4c4',
}

export const PRESETS: Preset[] = [
  {
    id: 'big-band',
    name: 'Big Band',
    layout: 'straight',
    sections: [],
    // Three straight rows: saxes (front, 5) → trombones (mid, 4) → trumpets (back, 4).
    // Standard big-band lead-in-the-middle ordering within each section.
    // Every player gets their own music stand.
    // Rows are shifted right (straightOffset) and spread a little so the
    // rhythm section (piano / drums / amps) sits clear on the left.
    // The lead players (Alto 1 / Tbn 1 / Tpt 1) are lined up in one vertical
    // column — "playing over the head", how most big-band directors want it.
    // Alto 1 is the centre of the 5 saxes, so the sax row's offset is set so
    // that centre lands on the brass leads' column (Tbn 1 / Tpt 1, index 1 of 4).
    customRows: [
      {
        label: 'A',
        straightSpacing: 58.75,
        straightOffset: 64.5,
        chairs: [
          { label: 'Tnr 1',  color: COLORS.woodwind, hasStand: true },
          { label: 'Alto 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Alto 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Tnr 2',  color: COLORS.woodwind, hasStand: true },
          { label: 'Bari',   color: COLORS.woodwind, hasStand: true },
        ],
      },
      {
        label: 'B',
        straightSpacing: 63.67,
        straightOffset: 96.5,
        chairs: [
          { label: 'Tbn 2', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 3', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 4', color: COLORS.brass, hasStand: true },
        ],
      },
      {
        label: 'C',
        straightSpacing: 64.33,
        straightOffset: 96.5,
        chairs: [
          { label: 'Tpt 2', color: '#f4a261', hasStand: true, isStool: true },
          { label: 'Tpt 1', color: '#f4a261', hasStand: true, isStool: true },
          { label: 'Tpt 3', color: '#f4a261', hasStand: true, isStool: true },
          { label: 'Tpt 4', color: '#f4a261', hasStand: true, isStool: true },
        ],
      },
    ],
    instruments: [
      { type: 'bass-amp',   angle: -2.3121, distance: 316.8 },
      { type: 'drumkit',    angle: -1.9446, distance: 258.4 },
      { type: 'piano',      angle: -2.4155, distance: 233.3, rotation: 1.5708 },
      { type: 'guitar-amp', angle: -2.1855, distance: 164.4 },
    ],
  },
  {
    id: 'chamber-orchestra',
    name: 'Chamber Orchestra',
    layout: 'semicircle',
    sections: [],
    // Mozart-sized: 1 each of Fl/Ob/Cl/Bn, 2 horns, no perc, modest strings,
    // 1 bass sitting in the third row behind the cellos.
    notation: '1.1.1.1 - 2.0.0.0 - 0 - 6.5.4.3.1',
  },
  {
    id: 'symphony-orchestra',
    name: 'Symphony Orchestra',
    layout: 'semicircle',
    sections: [],
    // Late-romantic full symphony (Tchaikovsky-ish): triple winds, full
    // brass, full strings. The percussion block is dropped from the notation so
    // it isn't a row of chairs; instead the timpani sits as a fixed instrument
    // at the right-hand end of the back (brass) row (polar from conductor).
    notation: '3.3.3.3 - 4.3.3.1 - 14.12.10.8.6',
    instruments: [
      { type: 'timpani', angle: -1.16, distance: 760, count: 4 },
    ],
  },
  {
    id: 'concert-band',
    name: 'Concert Band',
    layout: 'semicircle',
    sections: [],
    // Four concentric rows fan back from the conductor with chair counts
    // 8 / 10 / 7 / 19 (front to back). Every player gets their own stand —
    // no shared desks in a concert band. The percussion section lives at
    // the back as a row of large fixed instruments (mallets, aux, drum
    // kit, timpani) plus a bass amp tucked behind the back row.
    customRows: [
      {
        label: 'A',
        chairs: [
          { label: 'Fl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Fl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Picc', color: COLORS.woodwind, hasStand: true },
          { label: 'Ob',   color: COLORS.woodwind, hasStand: true },
          { label: 'Ob',  color: COLORS.woodwind, hasStand: true },
        ],
      },
      {
        label: 'B',
        chairs: [
          { label: 'Cl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 1', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 2', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 3', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 3', color: COLORS.woodwind, hasStand: true },
          { label: 'Cl 3', color: COLORS.woodwind, hasStand: true },
          { label: 'B Cl', color: COLORS.woodwind, hasStand: true },
          { label: 'Bsn',  color: COLORS.woodwind, hasStand: true },
          { label: 'Bsn',  color: COLORS.woodwind, hasStand: true },
        ],
      },
      {
        label: 'C',
        // 7 saxes centred in 13 slots — 3 disabled placeholder chairs on
        // each side so the saxes cluster behind the clarinets instead of
        // stretching to the edges of the arc.
        chairs: [
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: 'AS 1', color: COLORS.woodwind, hasStand: true },
          { label: 'AS 1', color: COLORS.woodwind, hasStand: true },
          { label: 'AS 2', color: COLORS.woodwind, hasStand: true },
          { label: 'AS 2', color: COLORS.woodwind, hasStand: true },
          { label: 'TS',   color: COLORS.woodwind, hasStand: true },
          { label: 'TS',   color: COLORS.woodwind, hasStand: true },
          { label: 'BS',   color: COLORS.woodwind, hasStand: true },
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: '',     color: COLORS.woodwind, enabled: false },
          { label: '',     color: COLORS.woodwind, enabled: false },
        ],
      },
      {
        label: 'D',
        chairs: [
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Hn',    color: COLORS.brass, hasStand: true },
          { label: 'Tpt 3', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 3', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 2', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 2', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 1', color: COLORS.brass, hasStand: true },
          { label: 'Tpt 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 1', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 2', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 2', color: COLORS.brass, hasStand: true },
          { label: 'Tbn 3', color: COLORS.brass, hasStand: true },
          { label: 'Euph',  color: COLORS.brass, hasStand: true },
          { label: 'Euph',  color: COLORS.brass, hasStand: true },
          { label: 'Tuba',  color: COLORS.brass, hasStand: true },
          { label: 'Tuba',  color: COLORS.brass, hasStand: true },
        ],
      },
    ],
    instruments: [
      // Drum Kit and Aux at the top centre / centre-right.
      // Mallets curve around the LEFT side of the back arc, each rotated
      // so its long axis is tangent to the curve (radial-out from the
      // conductor). Timpani sits at the top-right; bass amp tucks in to
      // its lower-right, behind the euph/tuba area of the back chair row.
      // Polar coords from the conductor.
      { type: 'drumkit',  angle: -1.27, distance: 470 },
      { type: 'square',   angle: -1.55, distance: 440, label: 'Aux' },
      { type: 'mallet',   angle: -1.92, distance: 460, label: 'Glock',   rotation: -0.35 },
      { type: 'mallet',   angle: -2.22, distance: 445, label: 'Xylo',    rotation: -0.65 },
      { type: 'mallet',   angle: -2.53, distance: 445, label: 'Vibes',   rotation: -0.96 },
      { type: 'mallet',   angle: -2.80, distance: 445, label: 'Marimba', rotation: -1.23 },
      { type: 'timpani',  angle: -0.95, distance: 490, count: 4 },
      { type: 'bass-amp', angle: -0.37, distance: 435 },
    ],
  },
  {
    id: 'string-quartet',
    name: 'String Quartet',
    layout: 'semicircle',
    sections: [
      { name: 'Violin I',  instrument: 'Violin', count: 1, color: COLORS.strings, standMode: 'solo' },
      { name: 'Violin II', instrument: 'Violin', count: 1, color: COLORS.strings, standMode: 'solo' },
      { name: 'Viola',     instrument: 'Viola',  count: 1, color: COLORS.strings, standMode: 'solo' },
      { name: 'Cello',     instrument: 'Cello',  count: 1, color: COLORS.strings, standMode: 'solo' },
    ],
  },
]

// ---------------------------------------------------------------------------
// Section → Row packing
// ---------------------------------------------------------------------------

/**
 * Convert a preset + optional count overrides into a ChartConfig-ready row array.
 * Sections are packed into rows of maxPerRow chairs, colored by section.
 * Stands are applied per-section based on standMode (default 'solo').
 */
export function buildRowsFromSections(
  sections: PresetSection[],
  maxPerRow = 12,
): Row[] {
  // Flatten all chairs with stands applied per section
  const allChairs: Chair[] = []
  for (const section of sections) {
    const standMode = section.standMode ?? 'solo'
    for (let i = 0; i < section.count; i++) {
      const chair: Chair = {
        id: crypto.randomUUID(),
        enabled: true,
        color: section.color,
        label: section.instrument,
        hasStand: standMode === 'solo',
        standAfter: standMode === 'shared' && (i % 2 === 0) && (i + 1 < section.count),
      }
      allChairs.push(chair)
    }
  }

  // Pack into rows
  const rows: Row[] = []
  let i = 0
  const rowLabels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  while (i < allChairs.length) {
    const rowChairs = allChairs.slice(i, i + maxPerRow)
    rows.push({
      id: crypto.randomUUID(),
      chairs: rowChairs,
      label: rowLabels[rows.length] ?? String(rows.length + 1),
      fontSize: 11,
    })
    i += maxPerRow
  }

  return rows
}

// ---------------------------------------------------------------------------
// Boosey & Hawkes orchestra notation
//
// Format: `Ww - Br [- Perc] - Str` — each block is a dot-separated list of
// player counts. A count may carry a parenthesised doubling list, e.g.
// `3(III=Bass Clarinet)` or `2(I=Picc, II=Alto Fl)`.
//
// Examples:
//   2.2.2.2 - 4.2.3.1 - 1.2 - 12.10.8.8.6   (Brahms-sized)
//   1.1.1.1 - 2.0.0.0 - 0 - 6.5.4.3.2       (Mozart-sized chamber)
//   3.3.3.3 - 4.3.3.1 - 1.2 - 14.12.10.8.6  (Tchaikovsky-sized)
// ---------------------------------------------------------------------------

const ROMAN_TO_INT: Record<string, number> = {
  I: 1, II: 2, III: 3, IV: 4, V: 5, VI: 6, VII: 7, VIII: 8, IX: 9, X: 10,
}

interface ParsedInstrument {
  count: number
  doublings: Map<number, string>   // 1-indexed position → doubling label
}

interface ParsedSlot {
  name: string                     // canonical short name (e.g. "Fl")
  parsed: ParsedInstrument
}

export interface OrchestraComposition {
  woodwinds: ParsedSlot[]
  brass: ParsedSlot[]
  percussion: ParsedSlot[]
  strings: ParsedSlot[]
}

const WW_NAMES   = ['Fl', 'Ob', 'Cl', 'Bsn']
const BR_NAMES   = ['Hn', 'Tpt', 'Tbn', 'Tuba']
const PERC_NAMES = ['Timp', 'Perc']
const STR_NAMES  = ['Vln 1', 'Vln 2', 'Va', 'Vc', 'Cb']

function parseEntry(entry: string): ParsedInstrument {
  const trimmed = entry.trim()
  if (!trimmed || trimmed === '0') return { count: 0, doublings: new Map() }
  const m = trimmed.match(/^(\d+)(?:\((.+)\))?$/)
  if (!m) return { count: 0, doublings: new Map() }
  const count = parseInt(m[1], 10)
  const doublings = new Map<number, string>()
  if (m[2]) {
    for (const part of m[2].split(',').map(s => s.trim())) {
      const eq = part.indexOf('=')
      if (eq < 0) continue
      const posRaw = part.slice(0, eq).trim().toUpperCase()
      const label = part.slice(eq + 1).trim()
      const idx = ROMAN_TO_INT[posRaw] ?? parseInt(posRaw, 10)
      if (idx && label) doublings.set(idx, label)
    }
  }
  return { count, doublings }
}

function parseBlock(block: string, names: string[]): ParsedSlot[] {
  return block.split('.').map((entry, i) => ({
    name: names[i] ?? `?${i + 1}`,
    parsed: parseEntry(entry),
  }))
}

export function parseOrchestraNotation(notation: string): OrchestraComposition | null {
  const blocks = notation.split(/\s*-\s*/).map(b => b.trim()).filter(b => b)
  if (blocks.length < 3 || blocks.length > 4) return null
  let wwBlock: string, brBlock: string, percBlock: string | null = null, strBlock: string
  if (blocks.length === 3) {
    [wwBlock, brBlock, strBlock] = blocks
  } else {
    [wwBlock, brBlock, percBlock, strBlock] = blocks
  }
  return {
    woodwinds:  parseBlock(wwBlock,  WW_NAMES),
    brass:      parseBlock(brBlock,  BR_NAMES),
    percussion: percBlock ? parseBlock(percBlock, PERC_NAMES) : [],
    strings:    parseBlock(strBlock, STR_NAMES),
  }
}

/** Human-readable summary of a parsed composition, used by the modal preview. */
export function describeComposition(comp: OrchestraComposition): string {
  const longNames: Record<string, string> = {
    Fl: 'Flute', Ob: 'Oboe', Cl: 'Clarinet', Bsn: 'Bassoon',
    Hn: 'French Horn', Tpt: 'Trumpet', Tbn: 'Trombone', Tuba: 'Tuba',
    Timp: 'Timpani', Perc: 'Percussion',
    'Vln 1': 'Violin I', 'Vln 2': 'Violin II', Va: 'Viola', Vc: 'Cello', Cb: 'Double Bass',
  }
  const lines: string[] = []
  const fmtBlock = (label: string, slots: ParsedSlot[]) => {
    const parts = slots
      .filter(s => s.parsed.count > 0)
      .map(s => {
        const long = longNames[s.name] ?? s.name
        const dbl = [...s.parsed.doublings.entries()]
          .map(([pos, lab]) => `${pos === 1 ? 'I' : pos === 2 ? 'II' : pos === 3 ? 'III' : String(pos)}=${lab}`)
          .join(', ')
        const annot = dbl ? ` (${dbl})` : ''
        return `${s.parsed.count} ${long}${annot}`
      })
    if (parts.length) lines.push(`${label}: ${parts.join(', ')}`)
  }
  fmtBlock('Woodwinds',  comp.woodwinds)
  fmtBlock('Brass',      comp.brass)
  fmtBlock('Percussion', comp.percussion)
  fmtBlock('Strings',    comp.strings)
  const total = [...comp.woodwinds, ...comp.brass, ...comp.percussion, ...comp.strings]
    .reduce((s, slot) => s + slot.parsed.count, 0)
  lines.push(`Total: ${total} players`)
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Build rows from a parsed orchestra composition.
//
// Layout strategy (semicircle, conductor at front):
//  - Strings closest to the conductor (innermost arc), grouped together.
//    Larger orchestras split strings across multiple rows; smaller ones
//    pack all bowed strings into one front row with bass behind.
//  - Winds in 1–2 rows behind strings (Fl/Ob front, Cl/Bn back when wide).
//  - Brass behind winds.
//  - Percussion in the back row.
//
// Stand placement:
//  - Strings get shared stands (every two players share).
//  - Winds, brass, percussion get solo stands (one per player).
// ---------------------------------------------------------------------------

function makeChairFromSlot(slot: ParsedSlot, chairIndex: number, color: string, mode: 'solo' | 'shared'): Chair {
  const dbl = slot.parsed.doublings.get(chairIndex + 1)
  const label = dbl ? `${slot.name}/${dbl}` : slot.name
  return {
    id: crypto.randomUUID(),
    enabled: true,
    color,
    label,
    hasStand: mode === 'solo',
    standAfter: false,   // set later for shared mode at the row level
  }
}

// Number the players of each instrument section in a row so the 1st (principal)
// sits innermost — toward the centre of the row, where the conductor is — and
// the higher numbers fan out to the edges. Matches standard wind/brass seating.
// Only runs of ≥2 identical labels are numbered; soloists (e.g. a lone Tuba) and
// doubled chairs (whose labels differ) are left as-is.
function numberSections(chairs: Chair[]): void {
  const rowCenter = (chairs.length - 1) / 2
  let i = 0
  while (i < chairs.length) {
    const base = chairs[i].label
    if (!chairs[i].enabled || !base) { i++; continue }
    let j = i
    while (j < chairs.length && chairs[j].enabled && chairs[j].label === base) j++
    const n = j - i
    if (n >= 2) {
      // Section on the left of centre → 1st on its right (inner) edge; section
      // on the right → 1st on its left edge.
      const leftOfCentre = (i + j - 1) / 2 <= rowCenter
      for (let k = 0; k < n; k++) {
        chairs[i + k].label = `${base} ${leftOfCentre ? n - k : k + 1}`
      }
    }
    i = j
  }
}

function rowFromSlots(
  slots: ParsedSlot[],
  color: string,
  mode: 'solo' | 'shared',
  rowLabel: string,
): Row | null {
  const chairs: Chair[] = []
  for (const slot of slots) {
    if (!slot || slot.parsed.count === 0) continue
    const sectionStart = chairs.length
    for (let i = 0; i < slot.parsed.count; i++) {
      chairs.push(makeChairFromSlot(slot, i, color, mode))
    }
    // For shared mode, pair stands within this section only (so no shared
    // stand bridges across two different instrument groups in the same row).
    if (mode === 'shared') {
      for (let i = sectionStart; i + 1 < sectionStart + slot.parsed.count; i += 2) {
        chairs[i].standAfter = true
      }
    }
  }
  if (chairs.length === 0) return null
  return {
    id: crypto.randomUUID(),
    chairs,
    label: rowLabel,
    fontSize: 11,
  }
}

export interface OrchestraRowsResult {
  rows: Row[]
  /** Number of rows from the back to render as straight lines instead of arcs.
   *  Bowed string sections (V1/V2/Va/Vc) sit in the front arc; everything
   *  behind them (Cb, winds, brass, percussion) renders in straight rows so
   *  small sections like a pair of horns don't get stretched across the
   *  whole back of the stage. */
  straightRows: number
}

export function buildOrchestraRows(comp: OrchestraComposition): OrchestraRowsResult {
  const rows: Row[] = []
  const labels = 'ABCDEFGHIJKLMN'
  let arcRowCount = 0
  const pushRow = (chairs: Chair[], isArc: boolean) => {
    if (chairs.length === 0) return
    rows.push({
      id: crypto.randomUUID(),
      chairs,
      label: labels[rows.length] ?? String(rows.length + 1),
      fontSize: 11,
    })
    if (isArc) arcRowCount++
  }
  const pushSectionRow = (slots: ParsedSlot[], color: string, mode: 'solo' | 'shared', numbered = false) => {
    const r = rowFromSlots(slots, color, mode, '')
    if (r) {
      if (numbered) numberSections(r.chairs)
      pushRow(r.chairs, false)
    }
  }

  // ---- Strings: each section is its own contiguous wedge, fanned across ----
  // ---- the rows it needs. The renderer (`computeGroupLayout` in          ----
  // ---- renderer.ts) clusters chairs sharing a `group` tag into one      ----
  // ---- angular wedge per section, reserved at that section's GLOBAL max ----
  // ---- per-row population — so no placeholder/spacer chairs are needed  ----
  // ---- to shape the fan; the renderer does it from real chairs alone.   ----
  // Layout rules:
  //   * V1 | V2 | Va | (Vc → Cb) in left-to-right order. The rightmost
  //     group is shared: cellos fill it first, basses take over once
  //     cellos are placed.
  //   * Rows 0–3 get 1 desk per active section (a tight front for the
  //     principals). Rows 4+ get 2 desks per section (the section spreads
  //     back faster, matching real orchestra seating).
  //   * Within a section, an odd lone last chair gets its own solo stand
  //     instead of a half-desk.
  const v1 = comp.strings[0], v2 = comp.strings[1], va = comp.strings[2], vc = comp.strings[3], cb = comp.strings[4]
  const v1Desks = v1?.parsed.count ? Math.ceil(v1.parsed.count / 2) : 0
  const v2Desks = v2?.parsed.count ? Math.ceil(v2.parsed.count / 2) : 0
  const vaDesks = va?.parsed.count ? Math.ceil(va.parsed.count / 2) : 0
  const vcDesks = vc?.parsed.count ? Math.ceil(vc.parsed.count / 2) : 0
  const cbDesks = cb?.parsed.count ? Math.ceil(cb.parsed.count / 2) : 0
  const rightTotal = vcDesks + cbDesks

  if (v1Desks + v2Desks + vaDesks + rightTotal > 0) {
    // Returns the chairs for one desk position: a full desk (2 paired
    // chairs, tagged with `group`) or a lone last chair (1 chair, solo
    // stand). Empty once the section's real desks are exhausted.
    const oneDesk = (slot: ParsedSlot, deskIdx: number, group: string, asStool = false): Chair[] => {
      const startIdx = deskIdx * 2
      const remaining = slot.parsed.count - startIdx
      if (remaining >= 2) {
        const c1 = makeChairFromSlot(slot, startIdx,     COLORS.strings, 'shared')
        const c2 = makeChairFromSlot(slot, startIdx + 1, COLORS.strings, 'shared')
        c1.standAfter = true
        c1.group = group; c2.group = group
        if (asStool) { c1.isStool = true; c2.isStool = true }
        return [c1, c2]
      }
      if (remaining === 1) {
        const c = makeChairFromSlot(slot, startIdx, COLORS.strings, 'solo')
        c.group = group
        if (asStool) c.isStool = true
        return [c]
      }
      return []
    }

    // Each column tracks how many desks it has already placed, then hands
    // out up to `n` more on request — stopping once its real desks run out
    // (no padding; the renderer reserves the column's width regardless).
    let v1Used = 0, v2Used = 0, vaUsed = 0, rightUsed = 0
    const takeFrom = (
      slot: ParsedSlot | undefined,
      group: string,
      used: () => number,
      bump: () => void,
      total: number,
      n: number,
    ): Chair[] => {
      const out: Chair[] = []
      for (let i = 0; i < n && slot && used() < total; i++) {
        out.push(...oneDesk(slot, used(), group))
        bump()
      }
      return out
    }
    const takeRight = (n: number): Chair[] => {
      const out: Chair[] = []
      for (let i = 0; i < n; i++) {
        if (vc && rightUsed < vcDesks) {
          // Cellos and basses share the same angular lane ('right') so the
          // wedge stays consistent as the section transitions from vc to cb.
          out.push(...oneDesk(vc, rightUsed, 'right'))
          rightUsed++
        } else if (cb && rightUsed < rightTotal) {
          // Double basses play standing/perched, so seat them on stools.
          out.push(...oneDesk(cb, rightUsed - vcDesks, 'right', true))
          rightUsed++
        } else {
          break
        }
      }
      return out
    }

    let row = 0
    // Keep going until every active column has placed all its real desks.
    while (v1Used < v1Desks || v2Used < v2Desks || vaUsed < vaDesks || rightUsed < rightTotal) {
      const desksPerSection = row < 4 ? 1 : 2
      const rowChairs: Chair[] = []
      if (v1Desks > 0)    rowChairs.push(...takeFrom(v1, 'v1', () => v1Used, () => { v1Used++ }, v1Desks, desksPerSection))
      if (v2Desks > 0)    rowChairs.push(...takeFrom(v2, 'v2', () => v2Used, () => { v2Used++ }, v2Desks, desksPerSection))
      if (vaDesks > 0)    rowChairs.push(...takeFrom(va, 'va', () => vaUsed, () => { vaUsed++ }, vaDesks, desksPerSection))
      if (rightTotal > 0) rowChairs.push(...takeRight(desksPerSection))
      pushRow(rowChairs, true)
      row++
    }
  }

  // ---- Winds: solo stands, one or two straight rows ----
  const fl = comp.woodwinds[0], ob = comp.woodwinds[1], cl = comp.woodwinds[2], bn = comp.woodwinds[3]
  const totalWinds = comp.woodwinds.reduce((s, slot) => s + (slot?.parsed.count ?? 0), 0)
  const splitWinds = totalWinds > 6 &&
    ((fl?.parsed.count ?? 0) + (ob?.parsed.count ?? 0)) > 0 &&
    ((cl?.parsed.count ?? 0) + (bn?.parsed.count ?? 0)) > 0
  if (splitWinds) {
    pushSectionRow([fl, ob], COLORS.woodwind, 'solo', true)
    pushSectionRow([cl, bn], COLORS.woodwind, 'solo', true)
  } else if (totalWinds > 0) {
    pushSectionRow(comp.woodwinds, COLORS.woodwind, 'solo', true)
  }

  // ---- Brass: one straight row ----
  if (comp.brass.reduce((s, slot) => s + slot.parsed.count, 0) > 0) {
    pushSectionRow(comp.brass, COLORS.brass, 'solo', true)
  }

  // ---- Percussion: back straight row ----
  if (comp.percussion.reduce((s, slot) => s + slot.parsed.count, 0) > 0) {
    pushSectionRow(comp.percussion, COLORS.percussion, 'solo')
  }

  // Grouped rows keep their natural (compact) radii — the renderer spaces each
  // row's chairs by fixed pixels ("donut slice" layout), so desks never crowd
  // even at the front, and no radius fix-up is needed.
  return { rows, straightRows: rows.length - arcRowCount }
}

// ---------------------------------------------------------------------------
// Preset → materialised data
//
// A Preset is a declarative recipe — it can specify rows three different
// ways (notation > customRows > sections), plus optional fixed instruments.
// buildPreset takes one Preset and turns it into the concrete rows /
// instrument list that the renderer needs, without touching app state.
// Callers do whatever they want with the result (push history, assign to
// config, re-render…).
//
// Returns a discriminated union so the only expected failure mode (bad
// orchestra notation) is reported explicitly rather than thrown.
// ---------------------------------------------------------------------------

export type PresetBuild =
  | { ok: true; rows: Row[]; straightRows: number; instruments: FixedInstrument[] }
  | { ok: false; error: string }

export function buildPreset(preset: Preset): PresetBuild {
  let rows: Row[]
  // Default to whatever the preset declared; orchestra notation may override.
  let straightRows = preset.straightRows ?? 0

  if (preset.notation) {
    const comp = parseOrchestraNotation(preset.notation)
    if (!comp) return { ok: false, error: `Invalid orchestra notation: "${preset.notation}"` }
    const built = buildOrchestraRows(comp)
    rows = built.rows
    straightRows = built.straightRows
  } else if (preset.customRows && preset.customRows.length > 0) {
    const rowLetters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    rows = preset.customRows.map((row, i) => ({
      id: crypto.randomUUID(),
      chairs: row.chairs.map(c => ({
        id: crypto.randomUUID(),
        enabled: c.enabled ?? true,
        color: c.color,
        label: c.label,
        hasStand: c.hasStand ?? false,
        standAfter: c.standAfter ?? false,
        ...(c.isStool ? { isStool: true } : {}),
      })),
      label: row.label || rowLetters[i] || String(i + 1),
      fontSize: 11,
      ...(row.straightSpacing !== undefined ? { straightSpacing: row.straightSpacing } : {}),
      ...(row.straightOffset !== undefined ? { straightOffset: row.straightOffset } : {}),
    }))
  } else {
    rows = buildRowsFromSections(preset.sections.map(s => ({ ...s })))
  }

  const instruments: FixedInstrument[] = (preset.instruments ?? []).map(i => ({
    id: crypto.randomUUID(),
    type: i.type,
    angle: i.angle,
    distance: i.distance,
    rotation: i.rotation ?? 0,
    ...(i.count !== undefined ? { count: i.count } : {}),
    ...(i.label !== undefined ? { label: i.label } : {}),
  }))

  return { ok: true, rows, straightRows, instruments }
}
